return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 5,
  nextobjectid = 38,
  properties = {
    ["name"] = "Tesco - Room 1"
  },
  tilesets = {
    {
      name = "tesco_room",
      firstgid = 1,
      filename = "../tilesets/tesco_room.tsx"
    },
    {
      name = "castle",
      firstgid = 65,
      filename = "../tilesets/castle.tsx",
      exportfilename = "../tilesets/castle.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 28, 28, 28, 28, 4, 0, 0, 0, 2, 28, 28, 28, 0, 0,
        0, 0, 28, 28, 28, 28, 4, 0, 0, 0, 2, 28, 28, 28, 0, 0,
        0, 0, 28, 28, 28, 28, 12, 29, 29, 29, 10, 9, 9, 9, 0, 0,
        0, 0, 33, 33, 33, 33, 6, 29, 29, 29, 6, 6, 6, 14, 0, 0,
        0, 0, 33, 33, 33, 33, 29, 41, 41, 41, 29, 43, 43, 8, 0, 0,
        0, 0, 35, 35, 35, 35, 29, 29, 29, 29, 29, 29, 29, 8, 0, 0,
        0, 0, 5, 29, 29, 29, 29, 42, 42, 42, 29, 41, 41, 8, 0, 0,
        0, 0, 5, 33, 33, 29, 29, 29, 29, 29, 29, 29, 29, 8, 0, 0,
        0, 0, 5, 33, 33, 29, 29, 29, 29, 29, 29, 29, 29, 8, 0, 0,
        0, 0, 16, 7, 7, 7, 29, 29, 29, 29, 7, 7, 7, 15, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 29, 29, 8, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 5, 29, 29, 8, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 26,
          name = "spawn",
          type = "",
          shape = "point",
          x = 318.667,
          y = 359.863,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "entry",
          type = "",
          shape = "point",
          x = 340.477,
          y = 79.3639,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 30,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 441.037,
          y = 319.265,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* Items loom over this\nvery British-looking \nSupermarket.",
            ["text2"] = "* The power of helping\na little shines \nwithin you."
          }
        },
        {
          id = 31,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 279.97,
          y = -21.2041,
          width = 119.484,
          height = 40.0151,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "tesco_map_2",
            ["marker"] = "entry"
          }
        },
        {
          id = 34,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 283.521,
          y = 244.748,
          width = 110.882,
          height = 39.3942,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tesco_lobby.items",
            ["once"] = false
          }
        },
        {
          id = 36,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 80.871,
          y = 203.855,
          width = 162.378,
          height = 38.7884,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tesco_lobby.water",
            ["once"] = false
          }
        },
        {
          id = 37,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 115.311,
          y = 277.606,
          width = 87.878,
          height = 83.7884,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "tesco_lobby.checkout",
            ["once"] = false
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 400,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 150.852,
          y = 458.614,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 240,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 280,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 200,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 285,
          y = 240,
          width = 110,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 445,
          y = 240,
          width = 70,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 445,
          y = 160,
          width = 70,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 285,
          y = 160,
          width = 110,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 400,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 120,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 80,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 80,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 0,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 0,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 241.113,
          y = 471.927,
          width = 159.955,
          height = 14.5702,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
